// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pharmacy_api.Context;

#nullable disable

namespace pharmacy_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318174947_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("pharmacy_api.Entities.Category", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasMaxLength(550)
                        .HasColumnType("varchar(550)")
                        .HasColumnName("description");

                    b.Property<Guid>("idPharmacy")
                        .HasColumnType("char(36)")
                        .HasColumnName("id_pharmacy");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("updatedA")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("idPharmacy");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("pharmacy_api.Entities.Medication", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(550)
                        .HasColumnType("varchar(550)")
                        .HasColumnName("description");

                    b.Property<string>("dosage")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("dosage");

                    b.Property<Guid>("idCategory")
                        .HasColumnType("char(36)")
                        .HasColumnName("id_category");

                    b.Property<Guid>("idPharmacy")
                        .HasColumnType("char(36)")
                        .HasColumnName("id_pharmacy");

                    b.Property<string>("imageurl")
                        .HasMaxLength(350)
                        .HasColumnType("varchar(350)")
                        .HasColumnName("image_url");

                    b.Property<string>("manufacturer")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<bool?>("requirePrescription")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("require_prescription");

                    b.Property<int>("stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<string>("tags")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("tags");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("updatedA")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("idCategory");

                    b.ToTable("medications", (string)null);
                });

            modelBuilder.Entity("pharmacy_api.Entities.Pharmacy", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("address");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("city");

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cnpj");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<Guid>("idAdmin")
                        .HasColumnType("char(36)")
                        .HasColumnName("idAdmin");

                    b.Property<string>("logoUrl")
                        .HasMaxLength(350)
                        .HasColumnType("varchar(350)")
                        .HasColumnName("logo_url");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("passHash")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("pass_hash");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("phone");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("state");

                    b.Property<bool>("status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("updatedA")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("idAdmin")
                        .IsUnique();

                    b.ToTable("pharmacies", (string)null);
                });

            modelBuilder.Entity("pharmacy_api.Entities.User", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("passHash")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("updatedA")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("pharmacy_api.Entities.Category", b =>
                {
                    b.HasOne("pharmacy_api.Entities.Pharmacy", "pharmacy")
                        .WithMany("Categories")
                        .HasForeignKey("idPharmacy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pharmacy");
                });

            modelBuilder.Entity("pharmacy_api.Entities.Medication", b =>
                {
                    b.HasOne("pharmacy_api.Entities.Category", "category")
                        .WithMany("medicaments")
                        .HasForeignKey("idCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("pharmacy_api.Entities.Pharmacy", b =>
                {
                    b.HasOne("pharmacy_api.Entities.User", "admin")
                        .WithOne("pharmacy")
                        .HasForeignKey("pharmacy_api.Entities.Pharmacy", "idAdmin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("admin");
                });

            modelBuilder.Entity("pharmacy_api.Entities.Category", b =>
                {
                    b.Navigation("medicaments");
                });

            modelBuilder.Entity("pharmacy_api.Entities.Pharmacy", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("pharmacy_api.Entities.User", b =>
                {
                    b.Navigation("pharmacy");
                });
#pragma warning restore 612, 618
        }
    }
}
